before_install:
  - sudo apt-get install rpm
  - gem install package_cloud
  - sudo mkdir -p /opt/dcs-application
  
language: java

script:
  - package_cloud push fbrito/dcs/el/5 /home/travis/.m2/repository/com/terradue/ciop/app/dcs-doris-tsx/0.1/dcs-doris-tsx-0.1.rpm
