before_install:
  - sudo apt-get install rpm
  - gem install package_cloud
  - sudo mkdir -p /application
  - sudo chmod -R 777 /application
  
language: java

script:
  - package_cloud push fbrito/dcs/el/6/SRPMS /home/travis/.m2/repository/com/terradue/ciop/app/dcs-doris-tsx/0.1/dcs-doris-tsx-0.1.rpm
